version: '3'
services:
  redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  superset:
    image: amancevice/superset
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ""
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPERSET_ENV: dev
      # GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8088:8088
      - 5555:5555
    depends_on:
      - redis
    volumes:
      - ../config/:/home/superset/config/
volumes:
  mysql:
    external: false
  redis:
    external: false 